postgresql:
  enabled: false

externalDatabase:
  enabled: true

# Point the chart to your CNPG secret
externalDatabase:
  existingSecret: "postgres-cluster-app"
  existingSecretKey: "uri" # Change to match CNPG's secret key (e.g., uri, connection-string, or psql)

secret:
  create: false

server:
  env: []
